using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BraviaControl
{
    public static class RemoteControllerKeys
    {
        public const string Num1 = "AAAAAQAAAAEAAAAAAw==";
        public const string Num2 = "AAAAAQAAAAEAAAABAw==";
        public const string Num3 = "AAAAAQAAAAEAAAACAw==";
        public const string Num4 = "AAAAAQAAAAEAAAADAw==";
        public const string Num5 = "AAAAAQAAAAEAAAAEAw==";
        public const string Num6 = "AAAAAQAAAAEAAAAFAw==";
        public const string Num7 = "AAAAAQAAAAEAAAAGAw==";
        public const string Num8 = "AAAAAQAAAAEAAAAHAw==";
        public const string Num9 = "AAAAAQAAAAEAAAAIAw==";
        public const string Num0 = "AAAAAQAAAAEAAAAJAw==";
        public const string Num11 = "AAAAAQAAAAEAAAAKAw==";
        public const string Num12 = "AAAAAQAAAAEAAAALAw==";
        public const string Enter = "AAAAAQAAAAEAAAALAw==";
        public const string GGuide = "AAAAAQAAAAEAAAAOAw==";
        public const string ChannelUp = "AAAAAQAAAAEAAAAQAw==";
        public const string ChannelDown = "AAAAAQAAAAEAAAARAw==";
        public const string VolumeUp = "AAAAAQAAAAEAAAASAw==";
        public const string VolumeDown = "AAAAAQAAAAEAAAATAw==";
        public const string Mute = "AAAAAQAAAAEAAAAUAw==";
        public const string TvPower = "AAAAAQAAAAEAAAAVAw==";
        public const string Audio = "AAAAAQAAAAEAAAAXAw==";
        public const string MediaAudioTrack = "AAAAAQAAAAEAAAAXAw==";
        public const string Tv = "AAAAAQAAAAEAAAAkAw==";
        public const string Input = "AAAAAQAAAAEAAAAlAw==";
        public const string TvInput = "AAAAAQAAAAEAAAAlAw==";
        public const string TvAntennaCable = "AAAAAQAAAAEAAAAqAw==";
        public const string WakeUp = "AAAAAQAAAAEAAAAuAw==";
        public const string PowerOff = "AAAAAQAAAAEAAAAvAw==";
        public const string Sleep = "AAAAAQAAAAEAAAAvAw==";
        public const string Right = "AAAAAQAAAAEAAAAzAw==";
        public const string Left = "AAAAAQAAAAEAAAA0Aw==";
        public const string SleepTimer = "AAAAAQAAAAEAAAA2Aw==";
        public const string Analog2 = "AAAAAQAAAAEAAAA4Aw==";
        public const string TvAnalog = "AAAAAQAAAAEAAAA4Aw==";
        public const string Display = "AAAAAQAAAAEAAAA6Aw==";
        public const string Jump = "AAAAAQAAAAEAAAA7Aw==";
        public const string PicOff = "AAAAAQAAAAEAAAA+Aw==";
        public const string PictureOff = "AAAAAQAAAAEAAAA+Aw==";
        public const string Teletext = "AAAAAQAAAAEAAAA/Aw==";
        public const string Video1 = "AAAAAQAAAAEAAABAAw==";
        public const string Video2 = "AAAAAQAAAAEAAABBAw==";
        public const string AnalogRgb1 = "AAAAAQAAAAEAAABDAw==";
        public const string Home = "AAAAAQAAAAEAAABgAw==";
        public const string Exit = "AAAAAQAAAAEAAABjAw==";
        public const string PictureMode = "AAAAAQAAAAEAAABkAw==";
        public const string Confirm = "AAAAAQAAAAEAAABlAw==";
        public const string Up = "AAAAAQAAAAEAAAB0Aw==";
        public const string Down = "AAAAAQAAAAEAAAB1Aw==";
        public const string ClosedCaption = "AAAAAgAAAKQAAAAQAw==";
        public const string Component1 = "AAAAAgAAAKQAAAA2Aw==";
        public const string Component2 = "AAAAAgAAAKQAAAA3Aw==";
        public const string Wide = "AAAAAgAAAKQAAAA9Aw==";
        public const string EPG = "AAAAAgAAAKQAAABbAw==";
        public const string PAP = "AAAAAgAAAKQAAAB3Aw==";
        public const string TenKey = "AAAAAgAAAJcAAAAMAw==";
        public const string BSCS = "AAAAAgAAAJcAAAAQAw==";
        public const string Ddata = "AAAAAgAAAJcAAAAVAw==";
        public const string Stop = "AAAAAgAAAJcAAAAYAw==";
        public const string Pause = "AAAAAgAAAJcAAAAZAw==";
        public const string Play = "AAAAAgAAAJcAAAAaAw==";
        public const string Rewind = "AAAAAgAAAJcAAAAbAw==";
        public const string Forward = "AAAAAgAAAJcAAAAcAw==";
        public const string DOT = "AAAAAgAAAJcAAAAdAw==";
        public const string Rec = "AAAAAgAAAJcAAAAgAw==";
        public const string Return = "AAAAAgAAAJcAAAAjAw==";
        public const string Blue = "AAAAAgAAAJcAAAAkAw==";
        public const string Red = "AAAAAgAAAJcAAAAlAw==";
        public const string Green = "AAAAAgAAAJcAAAAmAw==";
        public const string Yellow = "AAAAAgAAAJcAAAAnAw==";
        public const string SubTitle = "AAAAAgAAAJcAAAAoAw==";
        public const string CS = "AAAAAgAAAJcAAAArAw==";
        public const string BS = "AAAAAgAAAJcAAAAsAw==";
        public const string Digital = "AAAAAgAAAJcAAAAyAw==";
        public const string Options = "AAAAAgAAAJcAAAA2Aw==";
        public const string Media = "AAAAAgAAAJcAAAA4Aw==";
        public const string Prev = "AAAAAgAAAJcAAAA8Aw==";
        public const string Next = "AAAAAgAAAJcAAAA9Aw==";
        public const string DpadCenter = "AAAAAgAAAJcAAABKAw==";
        public const string CursorUp = "AAAAAgAAAJcAAABPAw==";
        public const string CursorDown = "AAAAAgAAAJcAAABQAw==";
        public const string CursorLeft = "AAAAAgAAAJcAAABNAw==";
        public const string CursorRight = "AAAAAgAAAJcAAABOAw==";
        public const string ShopRemoteControlForcedDynamic = "AAAAAgAAAJcAAABqAw==";
        public const string FlashPlus = "AAAAAgAAAJcAAAB4Aw==";
        public const string FlashMinus = "AAAAAgAAAJcAAAB5Aw==";
        public const string AudioQualityMode = "AAAAAgAAAJcAAAB7Aw==";
        public const string DemoMode = "AAAAAgAAAJcAAAB8Aw==";
        public const string Analog = "AAAAAgAAAHcAAAANAw==";
        public const string Mode3D = "AAAAAgAAAHcAAABNAw==";
        public const string DigitalToggle = "AAAAAgAAAHcAAABSAw==";
        public const string DemoSurround = "AAAAAgAAAHcAAAB7Aw==";
        public const string StarAD = "AAAAAgAAABoAAAA7Aw==";
        public const string AudioMixUp = "AAAAAgAAABoAAAA8Aw==";
        public const string AudioMixDown = "AAAAAgAAABoAAAA9Aw==";
        public const string PhotoFrame = "AAAAAgAAABoAAABVAw==";
        public const string Tv_Radio = "AAAAAgAAABoAAABXAw==";
        public const string SyncMenu = "AAAAAgAAABoAAABYAw==";
        public const string Hdmi1 = "AAAAAgAAABoAAABaAw==";
        public const string Hdmi2 = "AAAAAgAAABoAAABbAw==";
        public const string Hdmi3 = "AAAAAgAAABoAAABcAw==";
        public const string Hdmi4 = "AAAAAgAAABoAAABdAw==";
        public const string TopMenu = "AAAAAgAAABoAAABgAw==";
        public const string PopUpMenu = "AAAAAgAAABoAAABhAw==";
        public const string OneTouchTimeRec = "AAAAAgAAABoAAABkAw==";
        public const string OneTouchView = "AAAAAgAAABoAAABlAw==";
        public const string DUX = "AAAAAgAAABoAAABzAw==";
        public const string FootballMode = "AAAAAgAAABoAAAB2Aw==";
        public const string iManual = "AAAAAgAAABoAAAB7Aw==";
        public const string Netflix = "AAAAAgAAABoAAAB8Aw==";
        public const string Assists = "AAAAAgAAAMQAAAA7Aw==";
        public const string ActionMenu = "AAAAAgAAAMQAAABLAw==";
        public const string Help = "AAAAAgAAAMQAAABNAw==";
        public const string TvSatellite = "AAAAAgAAAMQAAABOAw==";
        public const string WirelessSubwoofer = "AAAAAgAAAMQAAAB+Aw==";
    }

}
